apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-role-to-run-release-tests
rules:
  - verbs:
      - watch
      - get
      - list
    apiGroups:
      - operator.tekton.dev
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-role-binding
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user1
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user2
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user3
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user4
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user5
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user6
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user7
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user8
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user9
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: consoledeveloper
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: pipelinesdeveloper                     
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-role-to-run-release-tests
